global using BananaTracks.Domain.Abstractions;
global using BananaTracks.Domain.Configuration;
global using BananaTracks.Domain.Messaging;
global using BananaTracks.Domain.Security;
global using BananaTracks.Domain.ServiceBus;
global using Microsoft.Azure.Functions.Worker;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Options;
